version: "3.8"
services:
  app:
    build: .
    container_name: email-writer-container
    ports:
      - '8080:8080'
    environment:
      GEMINI_API_URL: ${GEMINI_API_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}